spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/exam?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&autoReconnectForPools=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: qwer1234!
  flyway:
    url: jdbc:mariadb://localhost:3306/exam
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read_date_timestamps_as_nanoseconds: false
